'use strict';
// Simulates automated teams to show how the game parameters affect outcomes.
// Run: node tools/balance-report.js            (prints and writes BALANCE.md)
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = f => JSON.parse(fs.readFileSync(path.join(root, 'data', f), 'utf8'));
const QF = require(path.join(root, 'games/quality-flow/engine.js'));
const controls = read('controls.json'), events = read('events.json');

const N = parseInt(process.argv[2] || '1000', 10);
const PRIORITY = ['C09', 'C03', 'C01', 'C08', 'C14', 'C02', 'C07', 'C04', 'C06', 'C12', 'C13', 'C15', 'C05', 'C10', 'C11'];
const CHEAPEST = controls.slice().sort((a, b) => a.cost - b.cost || a.id.localeCompare(b.id)).map(c => c.id);

function play(seed, order, over, disposition) {
  const g = QF.createGame(Object.assign({ seed, teams: 1 }, over || {}), controls, events, null);
  const r = QF.autoPlay(g, [{ order, disposition: disposition || 'redo' }])[0];
  return r.total;
}
function stats(arr) {
  const a = arr.slice().sort((x, y) => x - y), n = a.length, mean = a.reduce((s, v) => s + v, 0) / n;
  return { mean, p10: a[Math.floor(n * 0.1)], med: a[n >> 1], p90: a[Math.floor(n * 0.9)] };
}
function series(order, over, disp, n) { const out = []; for (let s = 1; s <= (n || N); s++) out.push(play(s, order, over, disp)); return out; }
function randomOrder(seed) { const r = QF.mulberry32(seed * 31 + 7); const a = PRIORITY.slice(); for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(r() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; }
const f1 = x => (Math.round(x * 10) / 10).toFixed(1);

let md = '# Quality Flow balance report\n\nGenerated by `node tools/balance-report.js` with ' + N + ' seeded runs per row. One automated team plays 12 rounds with default parameters unless stated. Scores include audit points.\n\n';

// 1. Strategies
const none = series('none');
const rows = [
  ['No controls', none],
  ['Six core controls only (C09, C03, C01, C08, C14, C02)', series(['C09', 'C03', 'C01', 'C08', 'C14', 'C02'])],
  ['Cheapest controls first', series(CHEAPEST)],
  ['Random purchase order', (() => { const o = []; for (let s = 1; s <= N; s++) o.push(play(s, randomOrder(s))); return o; })()],
  ['Priority order (detection and containment first)', series(PRIORITY)],
  ['Priority order, always scrap held items', series(PRIORITY, null, 'scrap')]
];
md += '## 1. Purchase strategies\n\n| Strategy | Mean | 10th percentile | Median | 90th percentile | Beats "no controls" |\n|---|---|---|---|---|---|\n';
rows.forEach(([name, arr]) => { const s = stats(arr); const wins = arr.filter((v, i) => v > none[i]).length; md += '| ' + name + ' | ' + f1(s.mean) + ' | ' + f1(s.p10) + ' | ' + f1(s.med) + ' | ' + f1(s.p90) + ' | ' + f1(100 * wins / N) + '% |\n'; });

// 2. Marginal value of each control, paired by seed (keyed dice make the pairing meaningful)
function marginal(over, nm) {
  const all = series(CONTROL_IDS, over, null, nm), allMean = stats(all).mean;
  const rows = controls.map(c => {
    const arr = series(CONTROL_IDS.filter(id => id !== c.id), over, null, nm);
    const d = all.map((v, i) => v - arr[i]);
    const mean = d.reduce((x, y) => x + y, 0) / nm;
    const sd = Math.sqrt(d.reduce((x, y) => x + (y - mean) * (y - mean), 0) / (nm - 1));
    return { id: c.id, name: c.name, cost: c.cost, delta: mean, se: sd / Math.sqrt(nm) };
  }).sort((x, y) => y.delta - x.delta);
  return { allMean, rows };
}
function marginalTable(m) {
  let t = '| Control | QP | Score lost without it | Standard error | Per QP |\n|---|---|---|---|---|\n';
  m.rows.forEach(r => { t += '| ' + r.id + ' ' + r.name + ' | ' + r.cost + ' | ' + f1(r.delta) + ' | ' + f1(r.se) + ' | ' + f1(r.delta / r.cost) + ' |\n'; });
  return t;
}
var CONTROL_IDS = PRIORITY;
const direct = marginal({ startingQP: 200 }, Math.min(N, 1000));
md += '\n## 2. Value of each control\n\nRuns are paired by seed. Differences smaller than about two standard errors are not distinguishable from chance.\n\n### 2a. Direct effect (budget not limiting)\n\nEvery control is owned from round 1 (starting QP 200) except the one named. The full set scores ' + f1(direct.allMean) + '. Includes the audit points the control earns.\n\n' + marginalTable(direct);
const budget = marginal(null, Math.min(N, 1000));
md += '\n### 2b. Under the real budget (opportunity cost)\n\nTeams buy in priority order as QP allows. Removing a control lets later controls arrive earlier, so a low or negative figure means the control is a poor use of its QP compared with the alternatives, not that it does harm. The full set scores ' + f1(budget.allMean) + '.\n\n' + marginalTable(budget);

// 3. Parameter sensitivity
const n3 = Math.min(N, 400);
const base = (over) => { const a = series(PRIORITY, over, null, n3), b = series('none', over, null, n3); return [stats(a).mean, stats(b).mean]; };
const defaults = QF.DEFAULT_CONFIG;
const scaleStages = f => defaults.stages.map(s => s.defectProb != null ? Object.assign({}, s, { defectProb: Math.min(1, s.defectProb * f) }) : s);
const sens = [
  ['Default parameters', {}],
  ['Escape penalty -10 (default -15)', { economics: { escape: -10 } }],
  ['Escape penalty -20', { economics: { escape: -20 } }],
  ['Held item released in error 10% (default 25%)', { economics: { erroneousRelease: 0.10 } }],
  ['Held item released in error 40%', { economics: { erroneousRelease: 0.40 } }],
  ['Stage defect probabilities x0.5', { stages: scaleStages(0.5) }],
  ['Stage defect probabilities x1.5', { stages: scaleStages(1.5) }],
  ['Redo success 50% (default 70%)', { economics: { redoSuccess: 0.5 } }],
  ['Starting QP 12 (default 20)', { startingQP: 12 }],
  ['Starting QP 30', { startingQP: 30 }],
  ['Work items per round 3 (default 4)', { workItemsReleasedPerRound: 3 }],
  ['Work items per round 5', { workItemsReleasedPerRound: 5 }]
];
md += '\n## 3. Parameter sensitivity\n\nMean score of a controlled team (priority purchases) and an uncontrolled team, with the gap between them (' + n3 + ' runs each).\n\n| Parameter change | Controlled | Uncontrolled | Gap |\n|---|---|---|---|\n';
sens.forEach(([label, over]) => { const [a, b] = base(over); md += '| ' + label + ' | ' + f1(a) + ' | ' + f1(b) + ' | ' + f1(a - b) + ' |\n'; });

md += '\n## Reading the results\n\n- Controls always beat no controls with the default parameters. The gap is large because every escape costs 15 points and one reputation point (worth 3 points at the end), and an uncontrolled team has many escapes.\n- Purchase order matters. The six core controls capture most of the benefit, and random or cheapest-first ordering scores noticeably lower than priority ordering. Table 2a shows that every control helps on its own; table 2b shows which ones are good uses of scarce QP. Use both in the debrief: for example, discuss why C10, C11 and C07 repay little in this model (they pay back through audit points, recurrence and early detection rather than direct savings), and why C09 is worth far more than its price.\n- Tuning suggestion: C07 (in-process check at the constraint) is the weakest purchase under the default parameters. To make the constraint lesson stronger, raise `inProcessDetect`, raise the cost of defects found after the constraint (`constraintScrapExtra`), or set `workItemsReleasedPerRound` above the constraint capacity.\n- The parameters that move outcomes most are the escape penalty, the stage defect probabilities, and the rate of erroneous release. To make the game closer, reduce the escape penalty or the defect probabilities in the configuration box on the setup screen.\n- Team choices change dice outcomes only through the controls owned, so the same seed with different choices shows the value of each control.\n';
fs.writeFileSync(path.join(root, 'BALANCE.md'), md);
console.log(md);
